include(FetchContent)
set(FETCHCONTENT_QUIET OFF)
FetchContent_Declare(yyjson URL https://github.com/ibireme/yyjson/archive/8b4a38dc994a110abaec8a400615567bd996105f.tar.gz)
FetchContent_Declare(sqlite URL https://sqlite.org/2026/sqlite-amalgamation-3530400.zip
  URL_HASH SHA3_256=628a44cfe82c66aed1ccbbe85a562d2e33ebe64b3288981ed76285612227934e)
FetchContent_Declare(treesitter URL https://github.com/tree-sitter/tree-sitter/archive/da6fe9beb4f7f67beb75914ca8e0d48ae48d6406.tar.gz)
FetchContent_Declare(tsgo URL https://github.com/tree-sitter/tree-sitter-go/archive/1547678a9da59885853f5f5cc8a99cc203fa2e2c.tar.gz)
# tomlc17 is the maintained successor to tomlc99. Pin both source and archive
# digest; Forge validates its small schema on top of the upstream TOML parser.
FetchContent_Declare(tomlc17
  URL https://codeload.github.com/cktan/tomlc17/tar.gz/64a063b8636a4b48d142f978270f5e53e605e240
  URL_HASH SHA256=7c6b268f1185d6c5f0ea9ae617370a81352a44060d0b1655aa6038266f72a6d1)
# SOURCE_SUBDIR deliberately skips upstream build systems: only these C sources
# are needed. FetchContent still supports user-supplied offline source paths.
foreach(dep yyjson sqlite treesitter tsgo tomlc17)
  FetchContent_GetProperties(${dep})
  if(NOT ${dep}_POPULATED)
    # Populate is used for CMake 3.24 compatibility with dependencies lacking
    # a CMake entrypoint. CMP0169 permits this on newer CMake versions.
    if(POLICY CMP0169)
      cmake_policy(SET CMP0169 OLD)
    endif()
    FetchContent_Populate(${dep})
  endif()
endforeach()
add_library(forge_json STATIC ${yyjson_SOURCE_DIR}/src/yyjson.c)
target_include_directories(forge_json PUBLIC ${yyjson_SOURCE_DIR}/src)
add_library(forge_toml STATIC ${tomlc17_SOURCE_DIR}/src/tomlc17.c)
target_include_directories(forge_toml PUBLIC ${tomlc17_SOURCE_DIR}/src)
if(MSVC)
  target_compile_definitions(forge_toml PRIVATE _CRT_SECURE_NO_WARNINGS)
endif()
add_library(forge_sqlite STATIC ${sqlite_SOURCE_DIR}/sqlite3.c)
target_include_directories(forge_sqlite PUBLIC ${sqlite_SOURCE_DIR})
target_compile_definitions(forge_sqlite PRIVATE SQLITE_ENABLE_FTS5 SQLITE_THREADSAFE=1 SQLITE_OMIT_LOAD_EXTENSION)
add_library(forge_treesitter STATIC ${treesitter_SOURCE_DIR}/lib/src/lib.c)
target_include_directories(forge_treesitter PUBLIC ${treesitter_SOURCE_DIR}/lib/include PRIVATE ${treesitter_SOURCE_DIR}/lib/src)
if(NOT WIN32)
  target_compile_definitions(forge_treesitter PRIVATE _DEFAULT_SOURCE _POSIX_C_SOURCE=200809L)
endif()
add_library(forge_go STATIC ${tsgo_SOURCE_DIR}/src/parser.c)
target_include_directories(forge_go PRIVATE ${tsgo_SOURCE_DIR}/src)
if(FORGE_WITH_LLAMA)
  set(LLAMA_BUILD_TESTS OFF CACHE BOOL "" FORCE)
  set(LLAMA_BUILD_EXAMPLES OFF CACHE BOOL "" FORCE)
  set(LLAMA_BUILD_TOOLS OFF CACHE BOOL "" FORCE)
  set(LLAMA_BUILD_SERVER OFF CACHE BOOL "" FORCE)
  set(LLAMA_CURL OFF CACHE BOOL "" FORCE)
  set(LLAMA_BUILD_COMMON ON CACHE BOOL "" FORCE)
  set(LLAMA_SUBPROCESS OFF CACHE BOOL "" FORCE)
  set(LLAMA_OPENSSL OFF CACHE BOOL "" FORCE)
  set(GGML_NATIVE OFF CACHE BOOL "" FORCE)
  set(BUILD_SHARED_LIBS OFF CACHE BOOL "" FORCE)
  FetchContent_Declare(llama URL https://github.com/ggml-org/llama.cpp/archive/bb4caa7540188872173c44d161602d9271386413.tar.gz)
  set(FORGE_LLAMA_PREBUILT "" CACHE PATH "Matching Windows llama.cpp DLL directory (optional)")
  if(FORGE_LLAMA_PREBUILT)
    if(NOT WIN32 OR NOT MSVC)
      message(FATAL_ERROR "FORGE_LLAMA_PREBUILT currently requires Windows/MSVC")
    endif()
    FetchContent_GetProperties(llama)
    if(NOT llama_POPULATED)
      FetchContent_Populate(llama)
    endif()
    find_package(Python3 COMPONENTS Interpreter REQUIRED)
    get_filename_component(msvc_bin "${CMAKE_C_COMPILER}" DIRECTORY)
    execute_process(COMMAND "${Python3_EXECUTABLE}" "${CMAKE_CURRENT_LIST_DIR}/../scripts/import_llama.py"
      "${FORGE_LLAMA_PREBUILT}" "${msvc_bin}" "${CMAKE_BINARY_DIR}/llama-imports"
      COMMAND_ERROR_IS_FATAL ANY)
    add_library(llama INTERFACE)
    target_include_directories(llama INTERFACE "${llama_SOURCE_DIR}/include" "${llama_SOURCE_DIR}/ggml/include")
    target_compile_definitions(llama INTERFACE LLAMA_SHARED GGML_SHARED)
    target_link_libraries(llama INTERFACE "${CMAKE_BINARY_DIR}/llama-imports/llama.lib" "${CMAKE_BINARY_DIR}/llama-imports/ggml.lib" "${CMAKE_BINARY_DIR}/llama-imports/ggml-base.lib")
    # The prebuilt package supplies the C runtime only. Build the matching
    # pinned common/Jinja library from source against those imported binaries.
    set(LLAMA_VERSION_BASE "0.2.0")
    set(LLAMA_VERSION_MAJOR 0)
    set(LLAMA_BUILD_NUMBER 0)
    set(LLAMA_BUILD_COMMIT "${llama_SOURCE_DIR}")
    set(LLAMA_ALL_WARNINGS OFF)
    set(LLAMA_FATAL_WARNINGS OFF)
    include("${llama_SOURCE_DIR}/cmake/license.cmake")
    # The top-level llama project normally provides this helper. The imported
    # runtime is already compiled, and Forge applies its own warnings, so the
    # pinned common sources need no additional global compile flags here.
    function(llama_add_compile_flags)
    endfunction()
    add_subdirectory("${llama_SOURCE_DIR}/vendor" "${CMAKE_BINARY_DIR}/llama-vendor" EXCLUDE_FROM_ALL)
    add_subdirectory("${llama_SOURCE_DIR}/common" "${CMAKE_BINARY_DIR}/llama-common" EXCLUDE_FROM_ALL)
  else()
    FetchContent_MakeAvailable(llama)
  endif()
endif()
